config/routes.rb
Rails.application.routes.draw do
  resources :appointments
	root 'doctors#index'
  resources :doctors
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :doctor_patients
	has_many :patients, through: :doctor_patients, source: :user
	has_many :appointments, through: :doctor_patients
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user_patient , only: [:index]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :speciality, :gender, :age)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :doctor_name %>
  </div>

  <div class="field">
    <%= form.label :speciality %>
    <%= form.text_field :speciality, id: :doctor_speciality %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, id: :doctor_gender %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age, id: :doctor_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h2 align="center">Doctors Near You</h2>
</br></br>

<div class="container">
    <div class="row">
        <% @doctors.each do |doctor| %> 
        <div class="col-md-3">
            <div class="doctor1">
                <img src="<%= doctor.image %>">
                <div class="doctor_image">
                    <h2 align="center"><%= doctor.name %></h2>
                </div>
                <div class="doctor_details">
                    <h4 align="center" class="doctor_content"><%=doctor.speciality %></h4>
                    <h4 align="center" class="doctor_content"><%=doctor.gender %></h4>
                     <%= button_to 'Book an Appointment', doctor, class: "btn btn-link read-more", :method => :get %>
                    
                </div>   
            </div> 
        </div>
        <% end %>
    </div>
</div>
</section>

<br>



<style type="text/css">

section
{
    padding: 20px 0;
    width: 100%;
    float: left;
}

.doctor_image {
    width: 100%;
    float: left;
}

.doctor_image img {
    width: 100%;
    float: left;
    padding: 10px;
}

h4 {
    text-transform: capitalize;
    font-weight: 600;
    color: #2a941f;
}
.doctor_details {
    width: 100%;
    float: left;
}

.doctor_details p {
    font-size: 16px;
    padding: 10px;
}
.read-more a {
    font-size: 18px;
    color: #1a7544;
    text-transform: capitalize;
    letter-spacing: .5;
}
.publication_date {
    padding: 0 10px;
    font-size: 15px;
    font-weight: 600;
}
.doctor1 {
    width: 100%;
    float: left;
    border-radius: 8px;
    box-shadow: 0px 5px 4px 2px #868282;
}
.read-more {
    margin-bottom: 15px;
}
img, svg {
    vertical-align: middle;
    width: 100%;
    height: 142px;
}

</style>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>
<%= button_to 'Back', doctors_path, :method => :get  %>

<p>
  <img src="<%= @doctor.image %>">
</p>
<p>
  <%= @doctor.name %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @doctor.speciality %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @doctor.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @doctor.age %>
</p>

<%= button_to 'Book an Appointment',new_appointment_path, class: "btn btn-link read-more", :method => :get %>